name: Laravel

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  Back-End-Laravel-Tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: ./

      - name: Update Dependencies
        run: composer update
        working-directory: ./

      - name: Install Dependencies
        run: composer install
        working-directory: ./

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./

      - name: Update .env for MySQL
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env
        working-directory: ./

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
            echo 'waiting for mysql to be ready...'
            sleep 5
          done

      - name: Run Migrations
        run: php artisan migrate --force
        working-directory: ./

      - name: Run NPM
        run: npm ci
        working-directory: ./
